AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Catalog: EC2 Reference Architecture(fdp-1oc5f3ula).'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: General Configuration
      Parameters:
      - VPC
      - KeyPair
      - RemoteAccessCIDR
    - Label:
        default: Linux Instance Configuration
      Parameters:
      - LinuxInstanceType
      - LinuxSubnet
      - LinuxSSHPort
      - LatestAmiId
    ParameterLabels:
      KeyPair:
        default: Key Pair
      LatestAmiId:
        default: SSM key to the latest Amazon linux AMI
      LinuxInstanceType:
        default: Linux Instance Type
      LinuxSSHPort:
        default: Linux SSH Port
      LinuxSubnet:
        default: Linux Subnet
      RemoteAccessCIDR:
        default: Remote Access CIDR Block
      VPC:
        default: VPC
Outputs:
  PublicIpAddress:
    Value:
      Fn::GetAtt:
      - LinuxInstance
      - PublicIp
  AWSRegionName:
    Value:
      Ref: AWS::Region
  IAMInstancePatchingRole:
    Value:
      Ref: InstancePatchingRole
  IAMPatchingInstanceProfile:
    Value:
      Ref: PatchingInstanceProfile
  KeyPair:
    Value:
      Ref: KeyPair
  LinuxInstanceAvailabilityZone:
    Value:
      Fn::GetAtt:
      - LinuxInstance
      - AvailabilityZone
  LinuxInstanceId:
    Value:
      Ref: LinuxInstance
  LinuxInstancePrivateIpAddress:
    Value:
      Fn::GetAtt:
      - LinuxInstance
      - PrivateIp
  LinuxInstanceType:
    Value:
      Ref: LinuxInstanceType
  LinuxSSHPort:
    Value:
      Ref: LinuxSSHPort
  LinuxSubet:
    Value:
      Ref: LinuxSubnet
  RemoteAccessCIDR:
    Value:
      Ref: RemoteAccessCIDR
  SSMLinuxPatchBaseline:
    Value:
      Ref: LinuxPatchBaseline
  SSMMaintenaceWindowRole:
    Value:
      Ref: MaintenanceWindowRole
  TemplateID:
    Value: service-catalog-reference-architectures/sc-ec2-ra
  VPC:
    Value:
      Ref: VPC
Parameters:
  KeyPair:
    Description: Name of existing EC2 key pair for Linux Instances
    Type: AWS::EC2::KeyPair::KeyName
  LatestAmiId:
    Default: ami-0e8c04af2729ff1bb
    Type: String
  LinuxInstanceType:
    AllowedValues:
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    Default: t3.micro
    Description: Amazon EC2 Linux Instance Type
    Type: String
  LinuxSSHPort:
    ConstraintDescription: must be 22 or a number from 1024 to 65535
    Default: 22
    Description: Linux SSH Port Number
    Type: Number
  LinuxSubnet:
    ConstraintDescription: must be an existing subnet
    Description: Select subnet for Linux Instance
    Type: AWS::EC2::Subnet::Id
  RemoteAccessCIDR:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: CIDR block to allow access to linux instances
    Type: String
  VPC:
    ConstraintDescription: must be an existing VPC
    Description: Select the VPC where the EC2 instances will be created
    Type: AWS::EC2::VPC::Id
Resources:
  InstancePatchingRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess
      Path: /
    Type: AWS::IAM::Role
  LinuxInstance:
    Properties:
      BlockDeviceMappings:
      - DeviceName: /dev/xvdh
        Ebs:
          Encrypted: true
          VolumeSize: '50'
      IamInstanceProfile:
        Ref: PatchingInstanceProfile
      ImageId:
        Ref: LatestAmiId
      InstanceType:
        Ref: LinuxInstanceType
      KeyName:
        Ref: KeyPair
      SecurityGroupIds:
      - Ref: LinuxSecurityGroup
      SubnetId:
        Ref: LinuxSubnet
      Tags:
      - Key: Name
        Value:
          Fn::Sub: SC-RA-Linux-${LinuxSubnet}
      - Key: Description
        Value: Service-Catalog-EC2-Reference-Architecture
    Type: AWS::EC2::Instance
  LinuxMainteanceWindowTarget:
    Properties:
      Description: Service Catalog EC2 Reference Architecture - Patch Maintenance
        for Amazon Linux Instances
      Name: sc-ec2-ra-linux-patch-targets
      OwnerInformation: Service Catalog EC2 Reference Architecture
      ResourceType: INSTANCE
      Targets:
      - Key: InstanceIds
        Values:
        - Ref: LinuxInstance
      WindowId:
        Ref: MaintenanceWindow
    Type: AWS::SSM::MaintenanceWindowTarget
  LinuxMaintenanceWindowTaskInstall:
    Properties:
      Description: 'Service Catalog EC2 Reference Architecture Maintenance Window
        Task: Install update for Amazon Linux Instance'
      MaxConcurrency: 1
      MaxErrors: 1
      Name: patch-sc-ec2-ra-linux-instances
      Priority: 2
      ServiceRoleArn:
        Fn::GetAtt:
        - MaintenanceWindowRole
        - Arn
      Targets:
      - Key: InstanceIds
        Values:
        - Ref: LinuxInstance
      TaskArn: AWS-RunPatchBaseline
      TaskParameters:
        Operation:
          Values:
          - Install
      TaskType: RUN_COMMAND
      WindowId:
        Ref: MaintenanceWindow
    Type: AWS::SSM::MaintenanceWindowTask
  LinuxMaintenanceWindowTaskScan:
    Properties:
      Description: 'Service Catalog EC2 Reference Architecture Maintenance Window
        Task: Scan for update for Amazon Linux Instance'
      MaxConcurrency: 1
      MaxErrors: 1
      Name: patch-sc-ec2-ra-linux-instances
      Priority: 1
      ServiceRoleArn:
        Fn::GetAtt:
        - MaintenanceWindowRole
        - Arn
      Targets:
      - Key: InstanceIds
        Values:
        - Ref: LinuxInstance
      TaskArn: AWS-RunPatchBaseline
      TaskParameters:
        Operation:
          Values:
          - Scan
      TaskType: RUN_COMMAND
      WindowId:
        Ref: MaintenanceWindow
    Type: AWS::SSM::MaintenanceWindowTask
  LinuxPatchBaseline:
    Properties:
      ApprovalRules:
        PatchRules:
        - ApproveAfterDays: 0
          ComplianceLevel: CRITICAL
          EnableNonSecurity: true
          PatchFilterGroup:
            PatchFilters:
            - Key: PRODUCT
              Values:
              - AmazonLinux2017.09
            - Key: CLASSIFICATION
              Values:
              - Security
              - Bugfix
              - Enhancement
              - Recommended
            - Key: SEVERITY
              Values:
              - Critical
              - Important
              - Medium
              - Low
      Description: Service Catalog EC2 Reference Architecture Patch Baseline for Amazon
        Linux instace
      Name: sc-ec2-ra-linux-patch-baseline
      OperatingSystem: AMAZON_LINUX
    Type: AWS::SSM::PatchBaseline
  LinuxSecurityGroup:
    Properties:
      GroupDescription: Enables SSH Access to Linux EC2 Instance
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        Description: allow all outgoing
        IpProtocol: '-1'
      SecurityGroupIngress:
      - CidrIp:
          Ref: RemoteAccessCIDR
        Description: allow SSH
        FromPort:
          Ref: LinuxSSHPort
        IpProtocol: tcp
        ToPort:
          Ref: LinuxSSHPort
      - CidrIp:
          Ref: RemoteAccessCIDR
        Description: allow icmp
        FromPort: '-1'
        IpProtocol: icmp
        ToPort: '-1'
      VpcId:
        Ref: VPC
    Type: AWS::EC2::SecurityGroup
  MaintenanceWindow:
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 2
      Description: Maintenance window to allow for patching Amazon Linux instances
      Duration: 6
      Name: sc-ec2-ra-linux-maintenance-window
      Schedule: cron(* 17 * * ? *)
    Type: AWS::SSM::MaintenanceWindow
  MaintenanceWindowRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
            - ssm.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole
      Path: /
    Type: AWS::IAM::Role
  PatchingInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: InstancePatchingRole
    Type: AWS::IAM::InstanceProfile